---
title: "s9-1-3 Analysis of translational regulation by the HIF2A/EIF4E2 axis"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
     fig_width: 5
     fig_height: 5
---


# Overview


```{r load_libraries, message = FALSE, warning = FALSE}

## Data visualization packages
library("ggrepel")
library("cowplot")
library("gghighlight")
## Parallelization oackages
## Specify the number of CPUs to be used
processors <- 8

temp <- sapply(list.files("../functions", full.names = TRUE), source)
temp <- sapply(list.files("../s8-analysis-of-translation/functions", full.names = TRUE), source, chdir = TRUE)
temp <- sapply(list.files("../s9-integrative-analysis/functions", full.names = TRUE), source)
source("../s6-differential-expression-and-tss-usage/functions/load_total_analysis_results.R", chdir = TRUE)

set.seed(0)

```


```{r define_directory}

annot.dir <- normalizePath(file.path("../../annotation/"))
annot.ps.dir <- file.path(annot.dir, "hg38_annotation/processed_data/")
annot.R.file <- list.files(
    annot.ps.dir,
    pattern = glob2rx("*primary_transcript_annotation*.rdata"),
    full.names = TRUE
)
load(annot.R.file)

results.dir <- file.path("../../results")
s4.tss.dir <- file.path(results.dir, "s4-tss-definition-and-tx-assignment")
s4.1.tss.def.dir <- file.path(s4.tss.dir, "s4-1-tss-definition")
s4.1.7.count.per.tss.dir <- file.path(s4.1.tss.def.dir, "s4-1-7-count-per-tss") 

s6.dir <- file.path(results.dir, "s6-differential-regulation-analysis")
s6.1.dir <- file.path(s6.dir, "s6-1-differentially-expressed-genes")

s8.dir <- file.path(results.dir, "s8-analysis-of-translation")
s8.1.dir <- file.path(s8.dir, "s8-1-differentially-translated-mRNAs")
s8.1.1.dir <- file.path(s8.1.dir, "gene-level-dte")
s8.3.dir <- file.path(s8.dir, "s8-3-validation-of-method")

s9.dir <- file.path(results.dir, "s9-integrative-analysis")

sq.dir <- file.path(results.dir, "sq-for-publication")
source.data.dir <- file.path(sq.dir, "sq1-source-data")
source.data.by.panel.dir <- file.path(source.data.dir, "by_panel")

create.dirs(
    c(
        s9.dir
    )
)

sample.file <- file.path("../../data/sample_data/processed_sample_file.csv")
sample.dt <- fread(sample.file)
sample.names <- sample.dt[, sample_name]

```

# Pre-processed data import


```{r load_preprocessed_data}

all.de.dte.res.dt <- fread(
    file.path(
        s9.dir,
        "all-differential-expression-and-translation-data.csv"
    ),
    na.strings = ""
)

all.de.dte.res.dt[, `:=`(
    VHL_target_RCC4 = factor(
        VHL_target_RCC4,
        levels = c("VHL_loss_repressed", "non_VHL_target", "VHL_loss_induced")
    ),
    mRNA_trsl_intersection_by_functions =  factor(
        mRNA_trsl_intersection_by_functions,
        levels = c("Glycolysis", "Vascular Process or Angiogenesis",
                   "Vascular Process", "Angiogenesis", "Others")
    )
)]

all.filtered.gene.dt <- fread(
    file.path(
        s8.3.dir,
        "filtered_gene_for_polysome_analysis.csv"
    )
)

## Reported EIF4E2/HIF2A targets
reported.eif4e2.target.dt <- fread(
    "../../data/others/20220210_previously_reported_HIF2A-EIF4E2_target_genes.csv"
)

```

# Analysis of the effect of EIF4E2 KO on global translational efficiency


```{r analyse_global_effect}

sl.comp.names <- c(
    "786O_VHL_xx_yy_NA__noEIF4E2_vs_EIF4E2",
    "786O_noVHL_xx_yy_NA__noEIF4E2_vs_EIF4E2"
)


intervention.names <- c(
    "786-O VHL:\nEIF4E2 KO",
    "786-O:\nEIF4E2 KO"
)

m.all.de.dte.res.dt <- trslWideToLong(
    all.de.dte.res.dt, sl.comp.names, intervention.names
)

m.all.de.dte.res.dt[, `:=`(
    filter_flag = case_when(
        variable == "MRL_log2fc_786O_VHL_xx_yy_NA__noEIF4E2_vs_EIF4E2" ~
            gene_id %in%
            intersect(
                all.filtered.gene.dt[c786O_VHL_EIF4E2_yy_NA == TRUE, gene_id],
                all.filtered.gene.dt[c786O_VHL_noEIF4E2_yy_NA == TRUE, gene_id]
            ),
        variable == "MRL_log2fc_786O_noVHL_xx_yy_NA__noEIF4E2_vs_EIF4E2" ~
            gene_id %in%
            intersect(
                all.filtered.gene.dt[c786O_noVHL_EIF4E2_yy_NA == TRUE, gene_id],
                all.filtered.gene.dt[c786O_noVHL_noEIF4E2_yy_NA == TRUE, gene_id]
            )
    )
)]

m.all.de.dte.res.dt <- m.all.de.dte.res.dt[filter_flag == TRUE]

temp <- plotTrslDistByIntervention(
    m.all.de.dte.res.dt = m.all.de.dte.res.dt,
    show.quantile = TRUE
)

print("The numbers of genes analysed:")
m.all.de.dte.res.dt[, table(Intervention)] %>% print

```

# Comparison of the effect of EIF4E2 KO with or without VHL


```{r comparisons of the effect of EIF4E2 KO}

eif4e2.dte.res.dt <- all.de.dte.res.dt[
    gene_id %in% all.filtered.gene.dt[
                     c786O_noVHL_EIF4E2_yy_NA == TRUE &
                     c786O_VHL_EIF4E2_yy_NA == TRUE &
                     c786O_noVHL_noEIF4E2_yy_NA == TRUE &
                     c786O_VHL_noEIF4E2_yy_NA == TRUE,
                     gene_id
                 ]
]

print(
    paste0(
        "The number of genes analysed: ",
        nrow(eif4e2.dte.res.dt[
            !is.na(MRL_log2fc_786O_VHL_xx_yy_NA__noEIF4E2_vs_EIF4E2) &
            !is.na(MRL_log2fc_786O_noVHL_xx_yy_NA__noEIF4E2_vs_EIF4E2)
        ])
    )
)

eif4e2.dte.res.dt %$%
    cor.test(
        x = MRL_log2fc_786O_VHL_xx_yy_NA__noEIF4E2_vs_EIF4E2,
        y = MRL_log2fc_786O_noVHL_xx_yy_NA__noEIF4E2_vs_EIF4E2,
        method = "pearson"
    )

ggplot(
    eif4e2.dte.res.dt,
    aes(
        x = MRL_log2fc_786O_VHL_xx_yy_NA__noEIF4E2_vs_EIF4E2,
        y = MRL_log2fc_786O_noVHL_xx_yy_NA__noEIF4E2_vs_EIF4E2
    )
) +
    geom_hline(yintercept = 0, color = "gray60") +
    geom_vline(xintercept = 0, color = "gray60") +
    geom_abline(slope = 1, intercept = 0, color = "gray60") +
    geom_point() +
    coord_cartesian(
        xlim = c(-1, 0.5), ylim = c(-1, 0.5)
    ) +
    gghighlight(
        gene_id %in% reported.eif4e2.target.dt[, gene_id],
        label_key = gene_name,
        label_params = list(size = 6, box.padding = 2)
    ) +
    theme(
        aspect.ratio = 1
    ) +
    xlab("MRL log2 fold change\nupon EIF4E2 inactivation in 786-O VHL") +
    ylab("MRL log2 fold change\nupon EIF4E2 inactivation in 786-O")


```


# Session information


```{r sessionInfo}

sessionInfo()

```
