---
title: "s9-2-1 Analysis of HIF dependent alternate TSS usage"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   html_document:
     highlight: haddock
     toc: yes
     toc_depth: 2
     keep_md: yes
     fig_width: 5
     fig_height: 5
---


# Overview

The changes in TSS usage of VHL dependent alternate TSS identified by the comparisons of RCC4 versus RCC4 
will be compared against the changes in other comparisons to examine the mode of action.

# Environment setup and data preprocessing

```{r load libraries, message = FALSE, warning = FALSE}

## Specify the number of CPUs to be used
processors <- 8

## library("BiocParallel")
## register(MulticoreParam(processors))

temp <- sapply(list.files("../functions", full.names = TRUE), source)
source(file.path("../s6-differential-expression-and-tss-usage/functions/load_total_analysis_results.R"), chdir = TRUE)

s4.tss.dir <- file.path(results.dir, "s4-tss-definition-and-tx-assignment")
s4.3.tx.info.dir <- file.path(s4.tss.dir, "s4-3-transcript-info")
s4.3.1.tx.info.rcc4.dir <- file.path(s4.3.tx.info.dir, "s4-3-1-transcript-info-for-RCC4")

s9.dir <- file.path(results.dir, "s9-integrative-analysis")

set.seed(0)

```


# Data import



```{r load data}

rcc4.vhl.loss.comparison.name <- "RCC4_xx_HIF1B_N__noVHL_vs_VHL"

sl.tss.de.res.dt <- tss.de.res.dt[
    comparison_name == rcc4.vhl.loss.comparison.name
]

sl.tss.de.res.dt[, `:=`(
    meanNormCount_treated_gene_sum = sum(meanNormCount_treated),
    meanNormCount_base_gene_sum = sum(meanNormCount_base)
), by = gene_id]

sl.tss.ratio.res.dt <- tss.ratio.res.dt[
    comparison_name == rcc4.vhl.loss.comparison.name
]

sl.diff.tss.res.dt <- diff.tss.res.dt[
    comparison_name == rcc4.vhl.loss.comparison.name
]

setnames(
    sl.tss.de.res.dt,
    old = c("log2fc", "shrlog2fc", "padj"),
    new = c("de_log2fc", "de_shrlog2fc", "de_padj")
)

sl.tss.all.res.dt <- merge(
    sl.tss.ratio.res.dt[, .(
        tss_name, gene_id, gene_name, 
        gene_FDR, tx_FDR, padj,
        proportion_treated, proportion_base,
        treated_basename, base_basename
    )],
    sl.tss.de.res.dt[, .(
        tss_name, de_log2fc, de_shrlog2fc, de_padj,
        meanNormCount_treated, meanNormCount_base,
        meanNormCount_treated_gene_sum, meanNormCount_base_gene_sum
    )],
    by = "tss_name"
) %>%
    merge(
        y = sl.diff.tss.res.dt[, .(
            gene_id, biotype, 
            diff_tss_with_threshold, alt_tss_reg_mode,
            tss_name_base, tss_name_alternative, discordant_flag
        )],
        by = "gene_id"
    ) %>%
    merge(
        y = filtered.tss.with.quantile.dt[, .(tss_name, annot, chr, strand, q50)],
        by = "tss_name"
    )

sl.tss.all.res.dt <- sl.tss.all.res.dt[biotype == "protein_coding"]
sl.tss.de.res.dt <- sl.tss.de.res.dt[biotype == "protein_coding"]

print("The number of significant events")
sl.tss.all.res.dt[!duplicated(gene_id), table(alt_tss_reg_mode)]

print("Discordant regulation")
sl.tss.all.res.dt[!duplicated(gene_id), table(discordant_flag)]

```



```{r alt base long comparison table export}

sl.tss.all.res.dt[, `:=`(
    dProportion = proportion_treated - proportion_base,
    base_alt_TSS_flag = case_when(
        tss_name == tss_name_base ~ "base_TSS",
        tss_name == tss_name_alternative ~ "alternative_TSS",
        TRUE ~ NA_character_
    ) %>%
        factor(levels = c("base_TSS", "alternative_TSS"))
)]

fwrite(
    sl.tss.all.res.dt,
    file.path(
        s9.dir,
        "alternative-vs-base-TSS-expression-regulation.csv"
    )
)


```


# Comparisons of alternate TSS usage across conditions


```{r cross sample comparison, fig.width = 9, fig.height = 7}

tss.ratio.res.dt[, dProportion := proportion_treated - proportion_base]

base.comparison <- rcc4.vhl.loss.comparison.name

compared.comparisons <- c(
    "786O_xx_HIF1B_N__noVHL_vs_VHL",
    "786O_xx_noHIF1B_N__noVHL_vs_VHL",
    "RCC4_VHL_HIF1B_xx__H_vs_N"
)

base.tss.ratio.res.dt <- tss.ratio.res.dt[
    comparison_name == base.comparison &
    tss_name %in% sl.tss.all.res.dt[base_alt_TSS_flag == "alternative_TSS", tss_name]
]

setnames(
    base.tss.ratio.res.dt,
    old = "dProportion",
    new = "base_dProportion"
)

compared.tss.ratio.res.dt <- tss.ratio.res.dt[
    comparison_name %in% compared.comparisons &
    tss_name %in% diff.tss.res.dt[comparison_name == base.comparison, tss_name_alternative]
]

base.comp.tss.ratio.res.dt <- merge(
    compared.tss.ratio.res.dt,
    base.tss.ratio.res.dt[, .(tss_name, base_dProportion)],
    by = "tss_name"
)

base.comp.tss.ratio.res.dt[, `:=`(
    plot_label = factor(
        plot_label,
        levels = paste0(
            str_split_fixed(compared.comparisons, "__", n = 2)[, 1],
            "\n(",
            str_split_fixed(compared.comparisons, "__", n = 2)[, 2],
            ")"
        )
    ),
    comparison_base = factor(
        comparison_base,
        levels = c(
            "RCC4_VHL_HIF1B", "786O_HIF1B_N", "786O_VHL_HIF1B",
            "786O_noHIF1B_N", "786O_VHL_noHIF1B"
        )
    )
)]

cor.dt <- base.comp.tss.ratio.res.dt[, list(
    cor.coef = cor.test(
        base_dProportion, dProportion,
        method = "pearson",
        alternative = "two.sided"
    )$estimate %>% round(digits = 2),
    cor.pvalue = cor.test(
        base_dProportion, dProportion,
        method = "pearson",
        alternative = "two.sided"
    )$p.value,
    plot_label = plot_label,
    comparison_base = comparison_base,
    sample_number = .N
),
    by = comparison_name
][!duplicated(comparison_name)]

print(cor.dt[, .(plot_label, cor.coef, cor.pvalue, sample_number)])

plotAltBaseTssChange <- function(c.comparison, base.comp.tss.ratio.res.dt){

    g1 <- ggplot(
        data = base.comp.tss.ratio.res.dt[
            comparison_name == c.comparison
        ],
        aes(
            x = base_dProportion,
            y = dProportion
        )
    ) +
        geom_vline(xintercept = 0, color = "gray60") +
        geom_hline(yintercept = 0, color = "gray60") +
        geom_abline(slope = 1, intercept = 0, color = "gray60") +
        geom_point(size = 1.5) +
        geom_smooth(method = "lm") +
        geom_text(
            data = cor.dt[comparison_name == c.comparison],
            aes(label = paste0(
                    "r = ", cor.coef, "\n(p ~ ",
                    formatC(cor.pvalue, format = "e", digits = 0) ,")"
                )),
            x = -0.3, y = 0.4
        ) +
        theme(
            aspect.ratio = 1
        ) +
        coord_cartesian(xlim = c(-0.5, 0.5), ylim = c(-0.5, 0.5)) +
        xlab("delta proportion of alternative TSS\nby VHL loss in RCC4") +
        ylab(c.comparison) +
        scale_x_continuous(guide = guide_axis(angle = 60), labels = scales::percent_format(accuracy = 1)) +
        scale_y_continuous(labels = scales::percent_format(accuracy = 1))

    return(g1)
}

temp <- lapply(
    compared.comparisons,
    plotAltBaseTssChange,
    base.comp.tss.ratio.res.dt = base.comp.tss.ratio.res.dt
)

cowplot::plot_grid(plotlist = temp, nrow = 1)

```



# Session information

```{r sessionInfo}

sessionInfo()

```
