---
title: "s8-3-1-2 Validation of method (single condition / comparisons between isoforms)"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
     fig_width: 5
     fig_height: 5
---


# Overview

Binary comparisons of the two most differentially translated mRNA isoforms from same gene will be performed.


```{r load_libraries, message = FALSE, warning = FALSE}

## Additional packages for parallelization
## Specify the number of CPUs to be used
processors <- 8
## library("BiocParallel")
## register(MulticoreParam(processors))

sig.th <- 0.05

temp <- sapply(list.files("../functions", full.names = TRUE), source)
source(
    "../s6-differential-expression-and-tss-usage/functions/load_total_analysis_results.R",
    chdir = TRUE
)

set.seed(0)

```


```{r define_directory}

sample.file <- file.path("../../data/sample_data/processed_sample_file.csv")

annot.dir <- normalizePath(file.path("../../annotation/"))
annot.ps.dir <- file.path(annot.dir, "hg38_annotation/processed_data/")
annot.R.file <- list.files(
    annot.ps.dir,
    pattern = glob2rx("*primary_transcript_annotation*.rdata"),
    full.names = TRUE
)
load(annot.R.file)

results.dir <- file.path("../../results")

s8.dir <- file.path(results.dir, "s8-analysis-of-translation")
s8.2.dte.iso.dir <- file.path(s8.dir, "s8-2-differentially-translated-isoforms")
s8.3.dir <- file.path(s8.dir, "s8-3-validation-of-method")

sq.dir <- file.path(results.dir, "sq-for-publication")
source.data.dir <- file.path(sq.dir, "sq1-source-data")
source.data.by.panel.dir <- file.path(source.data.dir, "by_panel")

sample.dt <- fread(sample.file)
sample.names <- sample.dt[, sample_name]

```

# Data import


```{r import_essential_data}

tss.level.mrl.master.dt <- fread(
    file = file.path(s8.3.dir, "tss_level_MRL_summary.csv")
)

dte.iso.dt <- file.path(
    s8.2.dte.iso.dir, "RCC4_VHL_EIF4E2_NA.csv"
) %>%
    fread

tss.level.mrl.master.dt <- merge(
    tss.level.mrl.master.dt,
    dte.iso.dt[, .(tss_name, biotype, gene_FDR, tx_FDR)],
    by = "tss_name"
)

```


# Data preparation for binary comparisons


```{r convert_table}

## Select isoform with statistically significant TE differences
mrna.quantile <- tss.level.mrl.master.dt[, quantile(meanNormCount_base, probs = 0.25)]

mrl.iso.master.dt <- tss.level.mrl.master.dt[tx_FDR < 0.1]

data.cols <- c(
    "MRL_base",
    "meanNormCount_base",
    "uORF_all", "first75mer_mMFEpn_G4p", 
    "tx_kozak_score"
)


## Select two isoforms with the largest translation differences
bin.mrl.iso.master.dt <- mrl.iso.master.dt[, `:=`(
    max_MRL = max(MRL_base),
    min_MRL = min(MRL_base)
), by = gene_id][
    max_MRL != min_MRL &
    (MRL_base == max_MRL | MRL_base == min_MRL)
][
  , `:=`(
        TE_flag = case_when(
            MRL_base == max_MRL ~ "higher_TE",
            MRL_base == min_MRL ~ "lower_TE"
        )
    )] %>%
    dcast(
    gene_id ~ TE_flag,
    value.var = data.cols
)

## Filter by expression level
bin.mrl.iso.master.dt <- bin.mrl.iso.master.dt[
    meanNormCount_base_higher_TE > mrna.quantile &
    meanNormCount_base_lower_TE > mrna.quantile
]

```


# Analysis of the enrichment of mRNA features in more or less efficiently translated isoforms


```{r enrichment_analaysis}

wilcoxTestForIsoformComparison <- function(sl.feature, bin.mrl.iso.master.dt){
    print(sl.feature)

    diff.bin.mrl.iso.master.dt <- 
        bin.mrl.iso.master.dt[
            get(paste0(sl.feature, "_higher_TE")) !=
            get(paste0(sl.feature, "_lower_TE"))
        ]

    diff.bin.mrl.iso.master.dt%>%
        nrow %>%
        {print(paste0("The number of genes analyzed: ", .))}

    wil.p <- diff.bin.mrl.iso.master.dt %$%
        wilcox.test(
            get(paste0(sl.feature, "_higher_TE")),
            get(paste0(sl.feature, "_lower_TE")),
            paired = TRUE,
            alternative = "two.sided"
        )$p.value

    long.bin.mrl.iso.master.dt <- melt(
        diff.bin.mrl.iso.master.dt,
        id.vars = "gene_id",
        measure.vars = c(
            paste0(sl.feature, "_higher_TE"),
            paste0(sl.feature, "_lower_TE")
        )
    ) %>%
        {.[
           , TE_higher := variable == paste0(sl.feature, "_higher_TE")
         ]}

    qylim.max <- long.bin.mrl.iso.master.dt[
      , boxplot.stats(value)$stats[5], by = TE_higher
    ][
        , max(V1)
    ]

    qylim.min <- long.bin.mrl.iso.master.dt[
      , boxplot.stats(value)$stats[1], by = TE_higher
    ][
        , min(V1)
    ]
    
    medan.sum <- long.bin.mrl.iso.master.dt[, median(value), by = TE_higher] 

    wil.r <- rcompanion::wilcoxonPairedRC(
                             x = long.bin.mrl.iso.master.dt[, value],
                             g = long.bin.mrl.iso.master.dt[, TE_higher] == FALSE,
                             paired = TRUE
                         )


    ## RBCC: rank biserial correlation coefficient
 
    res.sum.dt <- data.table(
        feature_name = sl.feature,
        p_value = wil.p,
        feature_value_higher_TE_median = medan.sum[TE_higher == TRUE, V1],
        feature_value_lower_TE_median = medan.sum[TE_higher == FALSE, V1],
        rbcc = unlist(wil.r["rc"])
    )

    return(res.sum.dt)
}

wil.test.res.dt <- lapply(
    data.cols[3:5],
    wilcoxTestForIsoformComparison,
    bin.mrl.iso.master.dt = bin.mrl.iso.master.dt
) %>%
    rbindlist

disp.f.name <- c("uORF number", "RNA structure (near cap)", "Kozak score")

wil.test.res.dt[, `:=`(
    display_feature_name = factor(disp.f.name, levels = rev(disp.f.name)),
    padj = p.adjust(p_value, method = "holm")
)] %>%
    {.[, sig_mark := case_when(
             padj < sig.th * 0.1 ~ "**",
             padj < sig.th ~ "*",
             TRUE ~ NA_character_
         )
     ]}

print(wil.test.res.dt)

ggplot(
    data = wil.test.res.dt,
    aes(
        x = rbcc,
        y = display_feature_name
    )
) +
    geom_bar(stat = "identity") +
    geom_vline(xintercept = 0, color = "black") +
    stat_summary(
        geom = 'text', aes(label = sig_mark),
        fun = max, hjust = c(-0.25, 1.5, 1.5), color = "black", size = 6
    ) +
    theme(
        aspect.ratio = 0.4,
        axis.title.y = element_blank()
    ) +
    xlab("Correlation coefficient (rb)") +
    coord_cartesian(xlim = c(-0.5, 0.5))

```




# Session information

```{r sessionInfo}

sessionInfo()

```
